### ISSUE TITLE
Unable to get the request working

### ISSUE THREAD

**Issue by arunatechtalk** [pawelrychlik/jira-dependency-graph#28]
Hello:

This may be a configuration issue. May not be a bug. But I dont have a contact info. So filing the bug.
Your help is appreciated.
I installed required software and executed this command. But getting these errors
1.Do i need to set up a proxy ?
2. What is the prerequisite i should check for. 
3. Should i be able to send a REST request to jira  with my user id and password?

Here is my request
python jira-dependency-graph.py --user=aruna.vempaty@oracle.com --password="xxxxxxx" --jira
=https://jira.oraclecorp.com OAM-25342

Fetching OAM-25342
Traceback (most recent call last):
  File "jira-dependency-graph.py", line 281, in <module>
    main()
  File "jira-dependency-graph.py", line 272, in main
    graph = graph + build_graph_data(issue, jira, options.excludes, options.show_directions, options.directions, options.includes, options.closed, options.ignore_epic, options.ignore_subtasks, options.traverse, options.word_wrap)
  File "jira-dependency-graph.py", line 199, in build_graph_data
    return walk(start_issue_key, [])
  File "jira-dependency-graph.py", line 149, in walk
    issue = jira.get_issue(issue_key)
  File "jira-dependency-graph.py", line 52, in get_issue
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

**Comment by pawelrychlik** [comment]
Hi @arunatechtalk, thanks for reaching out. I see two potential issues here:

1. The parameter `user` needs to be the your JIRA _Username_, not the email you normally use to log in. You can find the _Username_ in the Profile tab in your JIRA instance.
2. The URL you provided doesn't work for me. Make sure it's ok. Maybe it's only visible via VPN, and that's why I can't access it.

Let me know if this solves your problem!.
