### ISSUE TITLE
Link types not to follow?

### ISSUE THREAD

**Issue by quiram** [pawelrychlik/jira-dependency-graph#54]
Hi,

First of all, thanks a lot for this tool, I find it very useful for managing dependencies across tickets.

I was wondering if the following functionality is possible: I know I can mark certain link types so they aren't shown in the graph using `--exclude-link`, but this still walks the link and grabs the related tickets, which would then appear unlinked to anything else. I need the tool not to follow the excluded link at all, is there an option for this?

Many thanks!

**Comment by Regenhardt** [comment]
Hi, this isn't currently supported, but I definitely see the use case. You can open an issue on [my adaption](https://gitlab.com/Regenhardt/jiratools.net), or ideally implement it yourself so I can merge it. Since `--exclude-link` is already taken, how about `--cut-link` or something? Not sure how to name it both short and understandably.

**Comment by quiram** [comment]
I actually implemented this back in the day but modifying the existing python script. I'll open a PR with the changes in this repo, although I'm not confident it will be merged, it seems to be abandoned. You can then see the changes and adapt them for your C# code.

**Comment by Regenhardt** [comment]
Great, thanks!

**Comment by quiram** [comment]
PR available:
https://github.com/pawelrychlik/jira-dependency-graph/pull/55
